[
  ["C Corporation","Yes","Other"  ],
  ["Limited Liability Company","Yes","S-Corporation"  ],
  ["C Corporation","Yes","Limited Liability Company"  ],
  ["C Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["C Corporation","Yes","S-Corporation"  ],
  ["C Corporation","Yes","S-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["C Corporation","Yes","Limited Liability Company"  ],
  ["C Corporation","Yes","S-Corporation"  ],
  ["C Corporation","Yes","Limited Liability Company"  ],
  ["Limited Liability Company","Yes","S-Corporation"  ],
  ["Limited Liability Company","Yes","C-Corporation"  ],
  ["Limited Liability Company","Yes","C-Corporation"  ],
  ["Limited Liability Company","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["Limited Liability Company","Yes","C-Corporation"  ],
  ["C Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["C Corporation","Yes","S-Corporation"  ],
  ["Limited Liability Company","Yes","C-Corporation"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["C Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["Limited Liability Company","Yes","S-Corporation"  ],
  ["C Corporation","Yes","Limited Liability Company"  ],
  ["C Corporation","Yes","S-Corporation"  ],
  ["C Corporation","Yes","S-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["Limited Liability Company","Yes","S-Corporation"  ],
  ["C Corporation","Yes","S-Corporation"  ],
  ["Limited Liability Company","Yes","C-Corporation"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["Limited Liability Company","Yes","C-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["C Corporation","Yes","S-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","Other"  ],
  ["Limited Liability Company","Yes","Other"  ],
  ["Limited Liability Company","Yes","C-Corporation"  ],
  ["C Corporation","Yes","S-Corporation"  ],
  ["Limited Liability Company","Yes","S-Corporation"  ],
  ["Limited Liability Company","Yes","C-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","S-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["Other (please specify):","Yes","S-Corporation"  ],
  ["Limited Liability Company","Yes","S-Corporation"  ],
  ["C Corporation","Yes","S-Corporation"  ],
  ["C Corporation","Yes","Other"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["C Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["C Corporation","Yes","Other"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","S-Corporation"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["C Corporation","Yes","S-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["Limited Liability Company","Yes","Other"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["Limited Liability Company","Yes","S-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["Limited Liability Company","Yes","S-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["C Corporation","Yes","Limited Liability Company"  ],
  ["Limited Liability Company","Yes","S-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["C Corporation","Yes","S-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["Limited Liability Company","Yes","S-Corporation"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["C Corporation","Yes","Limited Liability Company"  ],
  ["C Corporation","Yes","Other"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","Other"  ],
  ["C Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["C Corporation","Yes","S-Corporation"  ],
  ["S Corporation","Yes","Other"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["Limited Liability Company","Yes","Limited Liability Company"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["S Corporation","Yes","C-Corporation"  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Other (please specify):","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["C Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["C Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["C Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["C Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["C Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["C Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","Yes",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["C Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["C Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["C Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["Other (please specify):","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Other (please specify):","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Other (please specify):","No",""  ],
  ["C Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Other (please specify):","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["C Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["S Corporation","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["Limited Liability Company","No",""  ],
  ["S Corporation","No",""  ]
]
